on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Create a file
        run: |
          touch key
          echo "${{ secrets.PASS }}" >> key
          cat key

      # - name: SSH into DigitalOcean Droplet
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.DROPLET_IP }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       ls
      # - name: Deploy to Droplet
      #   env:
      #     host: ${{ secrets.DROPLET_IP }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #   run: |
      #       scp -o StrictHostKeyChecking=no -i ${{ secrets.PASS }} -r $GITHUB_WORKSPACE/package.json $username@$host:/root
          
