on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: SSH into DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ls
      - name: Create SSH key directory and file
        run: |
          mkdir -p ~/.ssh
          echo -n "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Set up SSH key
        run: |
          eval `ssh-agent -s`
          ssh-add ~/.ssh/id_rsa
      - name: Deploy to Droplet
        env:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.SSH_USERNAME }}
        run: |
            scp -o StrictHostKeyChecking=no -r $GITHUB_WORKSPACE/package.json $username@$host:/hello
          
