on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: SSH into DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ls
      - name: Deploy to Droplet
        env:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PRIVATE_KEY}}
        run: |
            sshpass -p "$password" scp -o StrictHostKeyChecking=no -r $GITHUB_WORKSPACE/dist $username@$host:/root/dist_test/